version: '3'
services:
  api:
    container_name: soa_warehouse_service
#    image: leonardchinonso/soa-warehouse-service # use this only when referencing an already built image or image available on docker hub repository
    build: # Use build in place of image option
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
