version: '3'
services:
  api:
    container_name: soa_warehouse_service
    image: alaooluwatobi/soa_wh_service:latest
    build: # Use build in place of image option
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
